<a href="https://colab.research.google.com/github/charre2021/polars_work_on_cyber_attacks/blob/main/Cyber_Attacks_Financial_And_Market_Impact.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install cpi

In [128]:
import polars as pl
import polars.selectors as cs
import kagglehub
import requests
import os

In [4]:
path = kagglehub.dataset_download("aryanmdev/cyber-attacks-financial-and-market-impact")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/aryanmdev/cyber-attacks-financial-and-market-impact?dataset_version_number=1...

100%|██████████| 169k/169k [00:00<00:00, 53.5MB/s]

Extracting files...

In [14]:
files_list = os.listdir(path)
market_impact_path = os.path.join(path, files_list[0])
financial_impact_path = os.path.join(path, files_list[1])
incidents_master_path = os.path.join(path, files_list[2])

In [15]:
market_impact_raw = pl.read_csv(market_impact_path)

In [17]:
financial_impact_raw = pl.read_csv(financial_impact_path)

In [19]:
incidents_master_raw = pl.read_csv(incidents_master_path)

In [ ]:
financial_impact_raw.filter(pl.col("notes") != "null").select(pl.col("notes"))

In [ ]:
financial_impact_raw.filter(pl.col("created_at") != pl.col("created_at").first()).select(pl.col("created_at"))

In [ ]:
financial_impact_raw.filter(pl.col("updated_at") != pl.col("updated_at").first()).select(pl.col("updated_at"))

In [37]:
fi_remove_last_two_cols = financial_impact_raw.drop(["created_at","updated_at"])

In [43]:
fi_remove_last_two_cols.head()

shape: (5, 17)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ incident_i ┆ direct_los ┆ direct_los ┆ ransom_de ┆ … ┆ total_los ┆ inflation ┆ cpi_index ┆ notes │
│ d          ┆ s_usd      ┆ s_method   ┆ manded_us ┆   ┆ s_upper_b ┆ _adjusted ┆ _used     ┆ ---   │
│ ---        ┆ ---        ┆ ---        ┆ d         ┆   ┆ ound      ┆ _usd      ┆ ---       ┆ str   │
│ str        ┆ f64        ┆ str        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆       │
│            ┆            ┆            ┆ f64       ┆   ┆ f64       ┆ f64       ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ 2021-0508- ┆ 1.26e7     ┆ disclosed  ┆ 1.3803e7  ┆ … ┆ 4.3747e7  ┆ 2.9238e7  ┆ CPI-U     ┆ null  │
│ 001        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 2021      ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ (270.97)  ┆       │
│ 2025-1211- ┆ 7.6405e6   ┆ disclosed  ┆ null      ┆ … ┆ 1.8906e7  ┆ 1.5307e7  ┆ CPI-U     ┆ null  │
│ 001        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 2025      ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ (321.5)   ┆       │
│ 2023-0115- ┆ 3.4882e7   ┆ calculated ┆ null      ┆ … ┆ 1.0515e8  ┆ 7.5565e7  ┆ CPI-U     ┆ null  │
│ 001        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 2023      ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ (304.702) ┆       │
│ 2021-0315- ┆ 4.6822e6   ┆ disclosed  ┆ null      ┆ … ┆ 1.4525e7  ┆ 1.1098e7  ┆ CPI-U     ┆ null  │
│ 001        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 2021      ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ (270.97)  ┆       │
│ 2021-1204- ┆ 2.6846e6   ┆ estimated  ┆ null      ┆ … ┆ 6.7558e6  ┆ 6.4856e6  ┆ CPI-U     ┆ null  │
│ 001        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 2021      ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ (270.97)  ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

In [71]:
fi_add_date = fi_remove_last_two_cols.with_columns(pl.col("incident_id").str.extract(r"(\d{4}-\d{4})", 1).str.to_date("%Y-%m%d").alias("incident_date"))

In [149]:
CPI_U_2026 = 326.588

fi_add_year_and_cpi = fi_add_date.with_columns(
    (pl.col("cpi_index_used").str.extract(r"\s{1}(\d{4})", 1).cast(pl.Int32).alias("cpi_base_year")),
    (pl.col("cpi_index_used").str.extract(r"\((\d+\.\d+)\)", 1).cast(pl.Float64).alias("base_cpi")),
    )

fi_add_new_cpi = fi_add_year_and_cpi.with_columns(pl.lit(CPI_U_2026).alias("cpi_u_2026"))

In [150]:
fi_add_new_cpi

shape: (778, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ incident_ ┆ direct_lo ┆ direct_lo ┆ ransom_de ┆ … ┆ incident_ ┆ cpi_base_ ┆ base_cpi ┆ cpi_u_202 │
│ id        ┆ ss_usd    ┆ ss_method ┆ manded_us ┆   ┆ date      ┆ year      ┆ ---      ┆ 6         │
│ ---       ┆ ---       ┆ ---       ┆ d         ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ str       ┆ ---       ┆   ┆ date      ┆ i32       ┆          ┆ f64       │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 2021-0508 ┆ 1.26e7    ┆ disclosed ┆ 1.3803e7  ┆ … ┆ 2021-05-0 ┆ 2021      ┆ 270.97   ┆ 326.588   │
│ -001      ┆           ┆           ┆           ┆   ┆ 8         ┆           ┆          ┆           │
│ 2025-1211 ┆ 7.6405e6  ┆ disclosed ┆ null      ┆ … ┆ 2025-12-1 ┆ 2025      ┆ 321.5    ┆ 326.588   │
│ -001      ┆           ┆           ┆           ┆   ┆ 1         ┆           ┆          ┆           │
│ 2023-0115 ┆ 3.4882e7  ┆ calculate ┆ null      ┆ … ┆ 2023-01-1 ┆ 2023      ┆ 304.702  ┆ 326.588   │
│ -001      ┆           ┆ d         ┆           ┆   ┆ 5         ┆           ┆          ┆           │
│ 2021-0315 ┆ 4.6822e6  ┆ disclosed ┆ null      ┆ … ┆ 2021-03-1 ┆ 2021      ┆ 270.97   ┆ 326.588   │
│ -001      ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆          ┆           │
│ 2021-1204 ┆ 2.6846e6  ┆ estimated ┆ null      ┆ … ┆ 2021-12-0 ┆ 2021      ┆ 270.97   ┆ 326.588   │
│ -001      ┆           ┆           ┆           ┆   ┆ 4         ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ 2022-0508 ┆ 3.0337e6  ┆ disclosed ┆ null      ┆ … ┆ 2022-05-0 ┆ 2022      ┆ 292.655  ┆ 326.588   │
│ -002      ┆           ┆           ┆           ┆   ┆ 8         ┆           ┆          ┆           │
│ 2023-0310 ┆ 2.4538e7  ┆ estimated ┆ 7.5e7     ┆ … ┆ 2023-03-1 ┆ 2023      ┆ 304.702  ┆ 326.588   │
│ -002      ┆           ┆           ┆           ┆   ┆ 0         ┆           ┆          ┆           │
│ 2025-1112 ┆ 740926.8  ┆ estimated ┆ null      ┆ … ┆ 2025-11-1 ┆ 2025      ┆ 321.5    ┆ 326.588   │
│ -001      ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆          ┆           │
│ 2023-0620 ┆ 1.4747e7  ┆ calculate ┆ 5.7715e7  ┆ … ┆ 2023-06-2 ┆ 2023      ┆ 304.702  ┆ 326.588   │
│ -002      ┆           ┆ d         ┆           ┆   ┆ 0         ┆           ┆          ┆           │
│ 2021-0419 ┆ 9.4752105 ┆ calculate ┆ null      ┆ … ┆ 2021-04-1 ┆ 2021      ┆ 270.97   ┆ 326.588   │
│ -001      ┆ e7        ┆ d         ┆           ┆   ┆ 9         ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘